"""add_premium_until

Revision ID: d00d3f2f3c06
Revises: c5ec245b3a94
Create Date: 2026-05-25 09:28:24.130788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd00d3f2f3c06'
down_revision: Union[str, Sequence[str], None] = 'c5ec245b3a94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('premium_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'premium_until')
    # ### end Alembic commands ###
